// Generated by scripts/fit-howto.mjs from free-exercise-db
// (github.com/yuhonas/free-exercise-db, The Unlicense: public domain). Do not edit by hand.

export interface HowTo {
  /** The source exercise's name, which can differ a little from ours. */
  name: string;
  /** Start and finish positions, relative to the app's base path. */
  images: string[];
  steps: string[];
}

export const HOWTO: Record<string, HowTo> = {
  "incline-press": {
    "name": "Leverage Incline Chest Press",
    "images": [
      "howto/Leverage_Incline_Chest_Press-0.webp",
      "howto/Leverage_Incline_Chest_Press-1.webp"
    ],
    "steps": [
      "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the top of the pectorals at the beginning of the motion. Your chest and head should be up and your shoulder blades retracted. This will be your starting position.",
      "Press the handles forward by extending through the elbow.",
      "After a brief pause at the top, return the weight just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete."
    ]
  },
  "flat-press": {
    "name": "Leverage Chest Press",
    "images": [
      "howto/Leverage_Chest_Press-0.webp",
      "howto/Leverage_Chest_Press-1.webp"
    ],
    "steps": [
      "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the bottom or middle of the pectorals at the beginning of the motion.",
      "Your chest and head should be up and your shoulder blades retracted. This will be your starting position.",
      "Press the handles forward by extending through the elbow.",
      "After a brief pause at the top, return the weight just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete."
    ]
  },
  "cable-fly": {
    "name": "Cable Crossover",
    "images": [
      "howto/Cable_Crossover-0.webp",
      "howto/Cable_Crossover-1.webp"
    ],
    "steps": [
      "To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.",
      "Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.",
      "With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms and torso should remain stationary; the movement should only occur at the shoulder joint.",
      "Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.",
      "Hold for a second at the starting position and repeat the movement for the prescribed amount of repetitions."
    ]
  },
  "pec-fly": {
    "name": "Butterfly",
    "images": [
      "howto/Butterfly-0.webp",
      "howto/Butterfly-1.webp"
    ],
    "steps": [
      "Sit on the machine with your back flat on the pad.",
      "Take hold of the handles. Tip: Your upper arms should be positioned parallel to the floor; adjust the machine accordingly. This will be your starting position.",
      "Push the handles together slowly as you squeeze your chest in the middle. Breathe out during this part of the motion and hold the contraction for a second.",
      "Return back to the starting position slowly as you inhale until your chest muscles are fully stretched.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "dips": {
    "name": "Dips - Chest Version",
    "images": [
      "howto/Dips_-_Chest_Version-0.webp",
      "howto/Dips_-_Chest_Version-1.webp"
    ],
    "steps": [
      "For this exercise you will need access to parallel bars. To get yourself into the starting position, hold your body at arms length (arms locked) above the bars.",
      "While breathing in, lower yourself slowly with your torso leaning forward around 30 degrees or so and your elbows flared out slightly until you feel a slight stretch in the chest.",
      "Once you feel the stretch, use your chest to bring your body back to the starting position as you breathe out. Tip: Remember to squeeze the chest at the top of the movement for a second.",
      "Repeat the movement for the prescribed amount of repetitions."
    ]
  },
  "shoulder-press": {
    "name": "Leverage Shoulder Press",
    "images": [
      "howto/Leverage_Shoulder_Press-0.webp",
      "howto/Leverage_Shoulder_Press-1.webp"
    ],
    "steps": [
      "Load an appropriate weight onto the pins and adjust the seat for your height. The handles should be near the top of the shoulders at the beginning of the motion. Your chest and head should be up and handles held with a pronated grip. This will be your starting position.",
      "Press the handles upward by extending through the elbow.",
      "After a brief pause at the top, return the weight to just above the start position, keeping tension on the muscles by not returning the weight to the stops until the set is complete."
    ]
  },
  "lateral-raise": {
    "name": "Side Lateral Raise",
    "images": [
      "howto/Side_Lateral_Raise-0.webp",
      "howto/Side_Lateral_Raise-1.webp"
    ],
    "steps": [
      "Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.",
      "While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.",
      "Lower the dumbbells back down slowly to the starting position as you inhale.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "pushdown": {
    "name": "Triceps Pushdown",
    "images": [
      "howto/Triceps_Pushdown-0.webp",
      "howto/Triceps_Pushdown-1.webp"
    ],
    "steps": [
      "Attach a straight or angled bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.",
      "Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.",
      "Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.",
      "After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "oh-triceps": {
    "name": "Cable Rope Overhead Triceps Extension",
    "images": [
      "howto/Cable_Rope_Overhead_Triceps_Extension-0.webp",
      "howto/Cable_Rope_Overhead_Triceps_Extension-1.webp"
    ],
    "steps": [
      "Attach a rope to the bottom pulley of the pulley machine.",
      "Grasping the rope with both hands, extend your arms with your hands directly above your head using a neutral grip (palms facing each other). Your elbows should be in close to your head and the arms should be perpendicular to the floor with the knuckles aimed at the ceiling. This will be your starting position.",
      "Slowly lower the rope behind your head as you hold the upper arms stationary. Inhale as you perform this movement and pause when your triceps are fully stretched.",
      "Return to the starting position by flexing your triceps as you breathe out.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "lat-pulldown": {
    "name": "Wide-Grip Lat Pulldown",
    "images": [
      "howto/Wide-Grip_Lat_Pulldown-0.webp",
      "howto/Wide-Grip_Lat_Pulldown-1.webp"
    ],
    "steps": [
      "Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.",
      "Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.",
      "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
      "As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.",
      "After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.",
      "Repeat this motion for the prescribed amount of repetitions."
    ]
  },
  "pullup": {
    "name": "Pullups",
    "images": [
      "howto/Pullups-0.webp",
      "howto/Pullups-1.webp"
    ],
    "steps": [
      "Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.",
      "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
      "Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.",
      "After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.",
      "Repeat this motion for the prescribed amount of repetitions."
    ]
  },
  "high-row": {
    "name": "Leverage High Row",
    "images": [
      "howto/Leverage_High_Row-0.webp",
      "howto/Leverage_High_Row-1.webp"
    ],
    "steps": [
      "Load an appropriate weight onto the pins and adjust the seat height so that you can just reach the handles above you. Adjust the knee pad to help keep you down. Grasp the handles with a pronated grip. This will be your starting position.",
      "Pull the handles towards your torso, retracting your shoulder blades as you flex the elbow.",
      "Pause at the bottom of the motion, and then slowly return the handles to the starting position.",
      "For multiple repetitions, avoid completely returning the weight to the stops to keep tension on the muscles being worked."
    ]
  },
  "cs-row": {
    "name": "Leverage Iso Row",
    "images": [
      "howto/Leverage_Iso_Row-0.webp",
      "howto/Leverage_Iso_Row-1.webp"
    ],
    "steps": [
      "Load an appropriate weight onto the pins and adjust the seat height so that the handles are at chest level. Grasp the handles with either a neutral or pronated grip. This will be your starting position.",
      "Pull the handles towards your torso, retracting your shoulder blades as you flex the elbow.",
      "Pause at the bottom of the motion, and then slowly return the handles to the starting position. For multiple repetitions, avoid completely returning the weight to the stops to keep tension on the muscles being worked."
    ]
  },
  "cable-row": {
    "name": "Seated Cable Rows",
    "images": [
      "howto/Seated_Cable_Rows-0.webp",
      "howto/Seated_Cable_Rows-1.webp"
    ],
    "steps": [
      "For this exercise you will need access to a low pulley row machine with a V-bar. Note: The V-bar will enable you to have a neutral grip where the palms of your hands face each other. To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.",
      "Lean over as you keep the natural alignment of your back and grab the V-bar handles.",
      "With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise.",
      "Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "tbar-row": {
    "name": "T-Bar Row with Handle",
    "images": [
      "howto/T-Bar_Row_with_Handle-0.webp",
      "howto/T-Bar_Row_with_Handle-1.webp"
    ],
    "steps": [
      "Position a bar into a landmine or in a corner to keep it from moving. Load an appropriate weight onto your end.",
      "Stand over the bar, and position a Double D row handle around the bar next to the collar. Using your hips and legs, rise to a standing position.",
      "Assume a wide stance with your hips back and your chest up. Your arms should be extended. This will be your starting position.",
      "Pull the weight to your upper abdomen by retracting the shoulder blades and flexing the elbows. Do not jerk the weight or cheat during the movement.",
      "After a brief pause, return to the starting position."
    ]
  },
  "rear-delt-fly": {
    "name": "Reverse Machine Flyes",
    "images": [
      "howto/Reverse_Machine_Flyes-0.webp",
      "howto/Reverse_Machine_Flyes-1.webp"
    ],
    "steps": [
      "Adjust the handles so that they are fully to the rear. Make an appropriate weight selection and adjust the seat height so the handles are at shoulder level. Grasp the handles with your hands facing inwards. This will be your starting position.",
      "In a semicircular motion, pull your hands out to your side and back, contracting your rear delts.",
      "Keep your arms slightly bent throughout the movement, with all of the motion occurring at the shoulder joint.",
      "Pause at the rear of the movement, and slowly return the weight to the starting position."
    ]
  },
  "face-pull": {
    "name": "Face Pull",
    "images": [
      "howto/Face_Pull-0.webp",
      "howto/Face_Pull-1.webp"
    ],
    "steps": [
      "Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground."
    ]
  },
  "shrug": {
    "name": "Dumbbell Shrug",
    "images": [
      "howto/Dumbbell_Shrug-0.webp",
      "howto/Dumbbell_Shrug-1.webp"
    ],
    "steps": [
      "Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides.",
      "Lift the dumbbells by elevating the shoulders as high as possible while you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the dumbbells. Only the shoulders should be moving up and down.",
      "Lower the dumbbells back to the original position.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "preacher-curl": {
    "name": "Machine Preacher Curls",
    "images": [
      "howto/Machine_Preacher_Curls-0.webp",
      "howto/Machine_Preacher_Curls-1.webp"
    ],
    "steps": [
      "Sit down on the Preacher Curl Machine and select the weight.",
      "Place the back of your upper arms (your triceps) on the preacher pad provided and grab the handles using an underhand grip (palms facing up). Tip: Make sure that when you place the arms on the pad you keep the elbows in. This will be your starting position.",
      "Now lift the handles as you exhale and you contract the biceps. At the top of the position make sure that you hold the contraction for a second. Tip: Only the forearms should move. The upper arms should remain stationary and on the pad at all times.",
      "Lower the handles slowly back to the starting position as you inhale.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "hammer-curl": {
    "name": "Hammer Curls",
    "images": [
      "howto/Hammer_Curls-0.webp",
      "howto/Hammer_Curls-1.webp"
    ],
    "steps": [
      "Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso.",
      "The palms of the hands should be facing your torso. This will be your starting position.",
      "Now, while holding your upper arm stationary, exhale and curl the weight forward while contracting the biceps. Continue to raise the weight until the biceps are fully contracted and the dumbbell is at shoulder level. Hold the contracted position for a brief moment as you squeeze the biceps. Tip: Focus on keeping the elbow stationary and only moving your forearm.",
      "After the brief pause, inhale and slowly begin the lower the dumbbells back down to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "hack-squat": {
    "name": "Hack Squat",
    "images": [
      "howto/Hack_Squat-0.webp",
      "howto/Hack_Squat-1.webp"
    ],
    "steps": [
      "Place the back of your torso against the back pad of the machine and hook your shoulders under the shoulder pads provided.",
      "Position your legs in the platform using a shoulder width medium stance with the toes slightly pointed out. Tip: Keep your head up at all times and also maintain the back on the pad at all times.",
      "Place your arms on the side handles of the machine and disengage the safety bars (which on most designs is done by moving the side handles from a facing front position to a diagonal position).",
      "Now straighten your legs without locking the knees. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Begin to slowly lower the unit by bending the knees as you maintain a straight posture with the head up (back on the pad at all times). Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.",
      "Begin to raise the unit as you exhale by pushing the floor with mainly with the heel of your foot as you straighten the legs again and go back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "leg-press": {
    "name": "Leg Press",
    "images": [
      "howto/Leg_Press-0.webp",
      "howto/Leg_Press-1.webp"
    ],
    "steps": [
      "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.",
      "As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.",
      "Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.",
      "Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded."
    ]
  },
  "sl-leg-press": {
    "name": "Leg Press",
    "images": [
      "howto/Leg_Press-0.webp",
      "howto/Leg_Press-1.webp"
    ],
    "steps": [
      "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.",
      "As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.",
      "Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.",
      "Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded."
    ]
  },
  "leg-ext": {
    "name": "Leg Extensions",
    "images": [
      "howto/Leg_Extensions-0.webp",
      "howto/Leg_Extensions-1.webp"
    ],
    "steps": [
      "For this exercise you will need to use a leg extension machine. First choose your weight and sit on the machine with your legs under the pad (feet pointed forward) and the hands holding the side bars. This will be your starting position. Tip: You will need to adjust the pad so that it falls on top of your lower leg (just above your feet). Also, make sure that your legs form a 90-degree angle between the lower and upper leg. If the angle is less than 90-degrees then that means the knee is over the toes which in turn creates undue stress at the knee joint. If the machine is designed that way, either look for another machine or just make sure that when you start executing the exercise you stop going down once you hit the 90-degree angle.",
      "Using your quadriceps, extend your legs to the maximum as you exhale. Ensure that the rest of the body remains stationary on the seat. Pause a second on the contracted position.",
      "Slowly lower the weight back to the original position as you inhale, ensuring that you do not go past the 90-degree angle limit.",
      "Repeat for the recommended amount of times."
    ]
  },
  "rdl": {
    "name": "Stiff-Legged Dumbbell Deadlift",
    "images": [
      "howto/Stiff-Legged_Dumbbell_Deadlift-0.webp",
      "howto/Stiff-Legged_Dumbbell_Deadlift-1.webp"
    ],
    "steps": [
      "Grasp a couple of dumbbells holding them by your side at arm's length.",
      "Stand with your torso straight and your legs spaced using a shoulder width or narrower stance. The knees should be slightly bent. This is your starting position.",
      "Keeping the knees stationary, lower the dumbbells to over the top of your feet by bending at the waist while keeping your back straight. Keep moving forward as if you were going to pick something from the floor until you feel a stretch on the hamstrings. Exhale as you perform this movement",
      "Start bringing your torso up straight again by extending your hips and waist until you are back at the starting position. Inhale as you perform this movement.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "seated-curl": {
    "name": "Seated Leg Curl",
    "images": [
      "howto/Seated_Leg_Curl-0.webp",
      "howto/Seated_Leg_Curl-1.webp"
    ],
    "steps": [
      "Adjust the machine lever to fit your height and sit on the machine with your back against the back support pad.",
      "Place the back of lower leg on top of padded lever (just a few inches under the calves) and secure the lap pad against your thighs, just above the knees. Then grasp the side handles on the machine as you point your toes straight (or you can also use any of the other two stances) and ensure that the legs are fully straight right in front of you. This will be your starting position.",
      "As you exhale, pull the machine lever as far as possible to the back of your thighs by flexing at the knees. Keep your torso stationary at all times. Hold the contracted position for a second.",
      "Slowly return to the starting position as you breathe in.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "lying-curl": {
    "name": "Lying Leg Curls",
    "images": [
      "howto/Lying_Leg_Curls-0.webp",
      "howto/Lying_Leg_Curls-1.webp"
    ],
    "steps": [
      "Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.",
      "Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.",
      "As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.",
      "As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions."
    ]
  },
  "hip-thrust": {
    "name": "Barbell Hip Thrust",
    "images": [
      "howto/Barbell_Hip_Thrust-0.webp",
      "howto/Barbell_Hip_Thrust-1.webp"
    ],
    "steps": [
      "Begin seated on the ground with a bench directly behind you. Have a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise.",
      "Roll the bar so that it is directly above your hips, and lean back against the bench so that your shoulder blades are near the top of it.",
      "Begin the movement by driving through your feet, extending your hips vertically through the bar. Your weight should be supported by your shoulder blades and your feet. Extend as far as possible, then reverse the motion to return to the starting position."
    ]
  },
  "adduction": {
    "name": "Thigh Adductor",
    "images": [
      "howto/Thigh_Adductor-0.webp",
      "howto/Thigh_Adductor-1.webp"
    ],
    "steps": [
      "To begin, sit down on the adductor machine and select a weight you are comfortable with. When your legs are positioned properly on the leg pads of the machine, grip the handles on each side. Your entire upper body (from the waist up) should be stationary. This is the starting position.",
      "Slowly press against the machine with your legs to move them towards each other while exhaling.",
      "Feel the contraction for a second and begin to move your legs back to the starting position while breathing in. Note: Remember to keep your upper body stationary and avoid fast jerking motions in order to prevent any injuries from occurring.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "standing-calf": {
    "name": "Standing Calf Raises",
    "images": [
      "howto/Standing_Calf_Raises-0.webp",
      "howto/Standing_Calf_Raises-1.webp"
    ],
    "steps": [
      "Adjust the padded lever of the calf raise machine to fit your height.",
      "Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position.",
      "Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.",
      "Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "seated-calf": {
    "name": "Seated Calf Raise",
    "images": [
      "howto/Seated_Calf_Raise-0.webp",
      "howto/Seated_Calf_Raise-1.webp"
    ],
    "steps": [
      "Sit on the machine and place your toes on the lower portion of the platform provided with the heels extending off. Choose the toe positioning of your choice (forward, in, or out) as per the beginning of this chapter.",
      "Place your lower thighs under the lever pad, which will need to be adjusted according to the height of your thighs. Now place your hands on top of the lever pad in order to prevent it from slipping forward.",
      "Lift the lever slightly by pushing your heels up and release the safety bar. This will be your starting position.",
      "Slowly lower your heels by bending at the ankles until the calves are fully stretched. Inhale as you perform this movement.",
      "Raise the heels by extending the ankles as high as possible as you contract the calves and breathe out. Hold the top contraction for a second.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "cable-crunch": {
    "name": "Cable Crunch",
    "images": [
      "howto/Cable_Crunch-0.webp",
      "howto/Cable_Crunch-1.webp"
    ],
    "steps": [
      "Kneel below a high pulley that contains a rope attachment.",
      "Grasp cable rope attachment and lower the rope until your hands are placed next to your face.",
      "Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position.",
      "With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second.",
      "Slowly return to the starting position as you inhale. Tip: Make sure that you keep constant tension on the abs throughout the movement. Also, do not choose a weight so heavy that the lower back handles the brunt of the work.",
      "Repeat for the recommended amount of repetitions."
    ]
  },
  "back-ext": {
    "name": "Hyperextensions (Back Extensions)",
    "images": [
      "howto/Hyperextensions_Back_Extensions-0.webp",
      "howto/Hyperextensions_Back_Extensions-1.webp"
    ],
    "steps": [
      "Lie face down on a hyperextension bench, tucking your ankles securely under the footpads.",
      "Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction.",
      "With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms.",
      "Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. Tip: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back.",
      "Slowly raise your torso back to the initial position as you inhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury.",
      "Repeat for the recommended amount of repetitions."
    ]
  }
};
