// Builds src/lib/bodyPaths.ts, the anatomy behind the recovery map, from
// react-native-body-highlighter (MIT, github.com/HichamELBSI/react-native-body-highlighter).
// Re-run to refresh:  node scripts/bodymap.mjs

import { writeFileSync } from "node:fs";

const REPO = "https://raw.githubusercontent.com/HichamELBSI/react-native-body-highlighter/master";
const get = async (path) => {
  const res = await fetch(`${REPO}/${path}`);
  if (!res.ok) throw new Error(`${path}: ${res.status}`);
  return res.text();
};

// The asset files are TypeScript object literals; pull each region's slug
// and path strings out with patterns rather than evaluating the source.
function regions(source) {
  const out = [];
  for (const block of source.split(/\n\s*\{\s*\n\s*slug:/).slice(1)) {
    const slug = block.match(/^\s*"([a-z-]+)"/)?.[1];
    const d = [...block.matchAll(/"(M[^"]+)"/g)].map((m) => m[1]);
    if (slug && d.length) out.push({ slug, d });
  }
  return out;
}

const [front, back, wrapper, license] = await Promise.all([
  get("assets/bodyFront.ts"),
  get("assets/bodyBack.ts"),
  get("components/SvgMaleWrapper.tsx"),
  get("LICENSE"),
]);
const outlines = [...wrapper.matchAll(/d="([^"]+)"/g)].map((m) => m[1]);
if (outlines.length < 2) throw new Error("outline paths not found");

// Cropped to each figure (measured from the rendered paths, plus a margin).
const body = {
  front: { viewBox: "36 84 654 1278", outline: outlines[0], regions: regions(front) },
  back: { viewBox: "756 84 654 1278", outline: outlines[1], regions: regions(back) },
};
for (const side of ["front", "back"]) if (body[side].regions.length < 10) throw new Error(`${side}: too few regions`);

const notice = license.trim().split("\n").map((l) => (l ? `// ${l}` : "//")).join("\n");
writeFileSync("src/lib/bodyPaths.ts", `// Generated by scripts/bodymap.mjs. Do not edit by hand.
// Anatomy paths from react-native-body-highlighter
// (github.com/HichamELBSI/react-native-body-highlighter), used under its license:
//
${notice}

export interface BodyRegion {
  /** The source's region name: "chest", "deltoids", "upper-back", … */
  slug: string;
  d: string[];
}

export interface BodySide {
  viewBox: string;
  outline: string;
  regions: BodyRegion[];
}

export const BODY: Record<"front" | "back", BodySide> = ${JSON.stringify(body)};
`);
console.log(`front ${body.front.regions.length} regions, back ${body.back.regions.length} regions`);
