// Builds the /fit how-to photos and steps from free-exercise-db
// (github.com/yuhonas/free-exercise-db, The Unlicense: public domain).
// Re-run after changing MATCH:  node scripts/howto.mjs
// Writes public/howto/<id>-{0,1}.webp and src/lib/howto.ts.

import { mkdirSync, writeFileSync } from "node:fs";
import sharp from "sharp";

const SRC = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main";

// Our exercise id → free-exercise-db id. Picked to match the first machine
// the exercise routes to, and never a barbell deadlift.
const MATCH = {
  "incline-press": "Leverage_Incline_Chest_Press",
  "flat-press": "Leverage_Chest_Press",
  "cable-fly": "Cable_Crossover",
  "pec-fly": "Butterfly",
  dips: "Dips_-_Chest_Version",
  "shoulder-press": "Leverage_Shoulder_Press",
  "lateral-raise": "Side_Lateral_Raise",
  pushdown: "Triceps_Pushdown",
  "oh-triceps": "Cable_Rope_Overhead_Triceps_Extension",
  "lat-pulldown": "Wide-Grip_Lat_Pulldown",
  pullup: "Pullups",
  "high-row": "Leverage_High_Row",
  "cs-row": "Leverage_Iso_Row",
  "cable-row": "Seated_Cable_Rows",
  "tbar-row": "T-Bar_Row_with_Handle",
  "rear-delt-fly": "Reverse_Machine_Flyes",
  "face-pull": "Face_Pull",
  shrug: "Dumbbell_Shrug",
  "preacher-curl": "Machine_Preacher_Curls",
  "hammer-curl": "Hammer_Curls",
  "hack-squat": "Hack_Squat",
  "leg-press": "Leg_Press",
  "sl-leg-press": "Leg_Press",
  "leg-ext": "Leg_Extensions",
  rdl: "Stiff-Legged_Dumbbell_Deadlift",
  "seated-curl": "Seated_Leg_Curl",
  "lying-curl": "Lying_Leg_Curls",
  "hip-thrust": "Barbell_Hip_Thrust",
  adduction: "Thigh_Adductor",
  "standing-calf": "Standing_Calf_Raises",
  "seated-calf": "Seated_Calf_Raise",
  "cable-crunch": "Cable_Crunch",
  "back-ext": "Hyperextensions_Back_Extensions",
};

const all = await (await fetch(`${SRC}/dist/exercises.json`)).json();
const byId = new Map(all.map((e) => [e.id, e]));
mkdirSync("public/howto", { recursive: true });

const out = {};
const done = new Map();
for (const [ours, theirs] of Object.entries(MATCH)) {
  const e = byId.get(theirs);
  if (!e) throw new Error(`free-exercise-db has no ${theirs} (for ${ours})`);
  if (!done.has(theirs)) {
    const files = [];
    for (const [i, path] of e.images.slice(0, 2).entries()) {
      const res = await fetch(`${SRC}/exercises/${path}`);
      if (!res.ok) throw new Error(`${path}: ${res.status}`);
      const file = `${theirs}-${i}.webp`;
      await sharp(Buffer.from(await res.arrayBuffer())).resize({ width: 480, withoutEnlargement: true }).webp({ quality: 68 }).toFile(`public/howto/${file}`);
      files.push(`howto/${file}`); // relative to the app's base path
    }
    done.set(theirs, files);
  }
  out[ours] = { name: e.name, images: done.get(theirs), steps: e.instructions };
}

const ts = `// Generated by scripts/howto.mjs from free-exercise-db
// (github.com/yuhonas/free-exercise-db, The Unlicense: public domain). Do not edit by hand.

export interface HowTo {
  /** The source exercise's name, which can differ a little from ours. */
  name: string;
  /** Start and finish positions, relative to the app's base path. */
  images: string[];
  steps: string[];
}

export const HOWTO: Record<string, HowTo> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync("src/lib/howto.ts", ts);
console.log(`${Object.keys(out).length} exercises, ${done.size} photo pairs`);
